/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author gerso
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     * 
     * 
     * 
     * 
     */
    private String rol;
    
    public VistaMenu(String rol) {
        this.rol = rol;
        initComponents();
        this.setTitle("Menú");
        this.setLocationRelativeTo(null);
        botonesRol(rol);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregarUsers = new javax.swing.JButton();
        btnVistaInventario = new javax.swing.JButton();
        btnVistaProductos = new javax.swing.JButton();
        btnVistaVentas = new javax.swing.JButton();
        btnVistaClientes = new javax.swing.JButton();
        btnConsultaVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnHistorialInventario = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarUsers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregarUsers.setText("AGREGAR USUARIOS");
        btnAgregarUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsersActionPerformed(evt);
            }
        });

        btnVistaInventario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVistaInventario.setText("GESTIÓN DE INVENTARIO");
        btnVistaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaInventarioActionPerformed(evt);
            }
        });

        btnVistaProductos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVistaProductos.setText("GESTIÓN DE PRODUCTOS");
        btnVistaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaProductosActionPerformed(evt);
            }
        });

        btnVistaVentas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVistaVentas.setText("VENTAS");
        btnVistaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaVentasActionPerformed(evt);
            }
        });

        btnVistaClientes.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVistaClientes.setText("CLIENTES");

        btnConsultaVentas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConsultaVentas.setText("CONSULTA DE VENTAS");
        btnConsultaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaVentasActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnHistorialInventario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnHistorialInventario.setText("HIRTORIAL DE INVENTARIO");
        btnHistorialInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialInventarioActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnLogout.setText("CERRAR SESIÓN");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnVistaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVistaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorialInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVistaVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVistaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnConsultaVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVistaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVistaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistorialInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setText("MENÚ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonesRol(String rol) {
        btnAgregarUsers.setVisible(false);
        btnVistaClientes.setVisible(false);
        btnVistaInventario.setVisible(false);
        btnVistaProductos.setVisible(false);
        btnVistaVentas.setVisible(false);
        btnHistorialInventario.setVisible(false);
        btnReportes.setVisible(false);

        switch (rol.toLowerCase()) {
            case "admin":
                btnAgregarUsers.setVisible(true);
                btnVistaClientes.setVisible(true);
                btnVistaInventario.setVisible(true);
                btnVistaProductos.setVisible(true);
                btnVistaVentas.setVisible(true);
                btnReportes.setVisible(true);
                btnHistorialInventario.setVisible(true);
                break;

            case "supervisor":
                btnVistaInventario.setVisible(true);
                btnVistaProductos.setVisible(true);
                btnHistorialInventario.setVisible(true);
                break;
                
            case "vendedor":
                btnVistaVentas.setVisible(true);
                btnVistaClientes.setVisible(true);
                break;
            default:
                break;
                
                      
                

        }
    }
    private void btnAgregarUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsersActionPerformed

        VistaRegistroUsuarios registro = new VistaRegistroUsuarios();
        this.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_btnAgregarUsersActionPerformed

    private void btnVistaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaProductosActionPerformed
        // TODO add your handling code here:

        VistaProductos vistap = new VistaProductos();
        this.setVisible(false);
        vistap.setVisible(true);
    }//GEN-LAST:event_btnVistaProductosActionPerformed

    private void btnVistaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaInventarioActionPerformed
        // TODO add your handling code here:
        
        VistaInventario vistai = new VistaInventario();
        this.setVisible(false);
        vistai.setVisible(true);
                
    }//GEN-LAST:event_btnVistaInventarioActionPerformed

    private void btnVistaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaVentasActionPerformed
        VistaVentas vistaV = new VistaVentas();
        this.setVisible(false);
        vistaV.setVisible(true);
    }//GEN-LAST:event_btnVistaVentasActionPerformed

    private void btnConsultaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaVentasActionPerformed
        // TODO add your handling code here:
        VistaConsultaVentas vistaC = new VistaConsultaVentas();
        this.setVisible(false);
        vistaC.setVisible(true);
    }//GEN-LAST:event_btnConsultaVentasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        VistaReporteDelDia vistaR = new VistaReporteDelDia();
        this.setVisible(false);
        vistaR.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnHistorialInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialInventarioActionPerformed
        // TODO add your handling code here:
        VistaDetalleInventarios vistaI = new VistaDetalleInventarios();
        this.setVisible(false);
        vistaI.setVisible(true);
    }//GEN-LAST:event_btnHistorialInventarioActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        VistaLogin vistaL = new VistaLogin();
        this.setVisible(false);
        vistaL.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsers;
    private javax.swing.JButton btnConsultaVentas;
    private javax.swing.JButton btnHistorialInventario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVistaClientes;
    private javax.swing.JButton btnVistaInventario;
    private javax.swing.JButton btnVistaProductos;
    private javax.swing.JButton btnVistaVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
